"""Upgrade Repo & User Model

Revision ID: 28a2ee790e29
Revises: 755e7507817d
Create Date: 2026-06-28 18:00:13.829381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a2ee790e29'
down_revision: Union[str, None] = '755e7507817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('node_id', sa.String(), nullable=False))
    op.add_column('repos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_repos_node_id'), 'repos', ['node_id'])
    op.create_foreign_key(op.f('fk_repos_user_id_users'), 'repos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_repos_user_id_users'), 'repos', type_='foreignkey')
    op.drop_constraint(op.f('uq_repos_node_id'), 'repos', type_='unique')
    op.drop_column('repos', 'user_id')
    op.drop_column('repos', 'node_id')
    # ### end Alembic commands ###
