"""Upgrade Repo Model

Revision ID: 755e7507817d
Revises: a237435a29a5
Create Date: 2026-06-28 15:06:36.478960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755e7507817d'
down_revision: Union[str, None] = 'a237435a29a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('stargazers_count', sa.Integer(), nullable=False),
    sa.Column('watchers_count', sa.Integer(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('analyze', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repos')
    # ### end Alembic commands ###
